#pragma once

namespace Subject {

enum class Type {
  UNSPECIFIED = 0,
  PLAIN = 1,
  TEMP_EMITTER = 2,
  TURNABLE_TEMP_EMITTER = 3,
  LIGHT_EMITTER = 4,
  TURNABLE_LIGHT_EMITTER = 5,
  NETWORK_DEVICE = 6,
  INFRARED_CAMERA = 7,
  LIGHT_CAMERA = 8,
  TURNABLE = 9,
  AIR_TEMPERATURE_SENSOR = 10,
  ILLUMINATION_SENSOR = 11,
  WIRELESS_NETWORK_DEVICE = 12,
};

}
